### ISSUE TITLE
What is this for?

### ISSUE THREAD

**Issue by nullified33** [Merith-TK/minecraft.portable#1]
What is this meant to do.
Is this supposed to make a Minecraft version independent of the launcher?

**Comment by Merith-TK** [comment]
Nope, it is, with default config, supposed to download the official
launcher, and run it with command line flags, so that it keeps its data in
the same folder as the portable exe.

It also allows, after using the official launcher once, running any
minecraft launcher jar, or third party software that is normally not
portable (technic for example).

So basically, it just makes the official launcher portable.
